/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "firsttry.h"


void
firsttryprog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * firsttry_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIRSTTRYPROG, FIRSTTRYVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = firsttry_1(&firsttry_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


/**int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	firsttryprog_1 (host);
exit (0);
}*/

#include <stdio.h>
#include <string.h>
#include <rpc/rpc.h>
#include "firsttry.h"


int main (int argc, char *argv[]) 
{
	CLIENT *cl;
	char **p;
	char *msg;
	char *dir;
	char str1[50];
	char str2[50];
	if (argc != 4) 
	{
		printf("Usage: firstmain hostname filename server_directory\n");
		exit(1);
	}
	msg =argv[2];//filename
	dir =argv[3];//server directory
 	/**concatenate the directory & file name*/
	strcat(dir,msg);
	
	//strcat(str1, msg);
	strcat(str2, msg);
	
	/**rpc command to create client */
	cl = clnt_create(argv[1],FIRSTTRYPROG, FIRSTTRYVERS, "tcp");
	if (cl == NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	p = firsttry_1(&dir,cl);
	
	if (p == NULL)
	{
	    clnt_perror(cl,argv[1]);
	    exit(1);
	}
	FILE *fp;
	fp = fopen(str2,"w+");
	
	fputs(*p,fp);
	fclose(fp);
	printf("File = %s\n",*p);
exit(0);
}

